server:
  port: 8080
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: parking
        uri: lb://parking-service
        predicates:
        - Path=/parking/**
        filters:
        - StripPrefix=0
        - AddResponseHeader=Access-Control-Allow-Origin, *

      - id: parking-guide-plate
        uri: lb://parking-service
        predicates:
        - Path=/parking-guide/**
        filters:
        - StripPrefix=0
        - AddResponseHeader=Access-Control-Allow-Origin, *

      - id: vehicle
        uri: lb://vehicle-service
        predicates:
        - Path=/vehicle/**
        filters:
        - StripPrefix=0
        - AddResponseHeader=Access-Control-Allow-Origin, *

---
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true    
  instance:
    statusPageUrlPath: ${server.servlet.context-path}info
    healthCheckUrlPath: ${server.servlet.context-path}health
    metadataMap:
        deployment: local
        profile: local
        appType: gateway

---
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    statusPageUrlPath: ${server.servlet.context-path}info
    healthCheckUrlPath: ${server.servlet.context-path}health
    metadataMap:
        deployment: dev
        profile: dev
        appType: gateway
