---
image: "docker:latest"
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"

cache:
  paths:
  - ".m2/"

stages:
- "build"

build-mvn:
  image: "maven:3-jdk-8"
  stage: "build"
  script: "mvn package -U -B"