version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-reactive-processor
    ports:
      - "9092:9092"
    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
#      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  amano-eureka:
   build: ./amano-eureka/
   restart: always
   ports:
     - "8761:8761"
   environment:
     SPRING_PROFILES_ACTIVE: dev

  amano-gateway:
   depends_on:
     - amano-eureka
   build: ./amano-gateway/
   ports:
     - "8080:8080"
   restart: always
   environment:
     SPRING_PROFILES_ACTIVE: dev
     EUREKA_HOST: amano-eureka

  parking-service:
    depends_on:
      - amano-eureka
      - kafka
      - mongo
    build: ./parking-service/
    ports:
      - "9010:9010"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_HOST: amano-eureka
      KAFKA_HOST: kafka
      MONGO_HOST: mongo

  vehicle-service:
    depends_on:
      - amano-eureka
      - kafka
      - mongo
    build: ./vehicle-service/
    ports:
      - "9020:9020"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_HOST: amano-eureka
      KAFKA_HOST: kafka
      MONGO_HOST: mongo


